In [1]:
import pandas as pd

In [3]:
train = pd.read_csv("C:/Users/hp/Documents/Azubi_2/project_2/Customer_churn_prediction/data/training.csv")
test = pd.read_csv("C:/Users/hp/Documents/Azubi_2/project_2/Customer_churn_prediction/data/testing.csv")

In [4]:
train.shape , test.shape

((5043, 22), (2000, 21))

## Handling Missing Values

In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy= "median" )

In [7]:
train_num = train[["tenure", "MonthlyCharges", "TotalCharges"]] # selecting only numerical columns

In [8]:
train_num

tenure  MonthlyCharges  TotalCharges
0          1       29.850000     29.850000
1         34       56.950001   1889.500000
2          2       53.849998    108.150002
3         45       42.299999   1840.750000
4          2       70.699997    151.649994
...      ...             ...           ...
5038      24       84.800000   1990.500000
5039      72      103.200000   7362.900000
5040      11       29.600000    346.450000
5041       4       74.400000    306.600000
5042      66      105.650000   6844.500000

[5043 rows x 3 columns]

In [9]:
imputer.fit(train_num)

SimpleImputer(strategy='median')

In [10]:
imputer.statistics_

array([  29.        ,   70.55000305, 1401.4       ])

In [11]:
train_num.median().values

array([  29.        ,   70.55000305, 1401.4       ])

In [12]:
X = imputer.transform(train_num) # replacing median value if there

In [13]:
X

array([[1.00000000e+00, 2.98500004e+01, 2.98500004e+01],
       [3.40000000e+01, 5.69500008e+01, 1.88950000e+03],
       [2.00000000e+00, 5.38499985e+01, 1.08150002e+02],
       ...,
       [1.10000000e+01, 2.96000000e+01, 3.46450000e+02],
       [4.00000000e+00, 7.44000000e+01, 3.06600000e+02],
       [6.60000000e+01, 1.05650000e+02, 6.84450000e+03]])

In [14]:
train_tr = pd.DataFrame(X, columns=train_num.columns) # converting to data frame

In [15]:
train_tr

tenure  MonthlyCharges  TotalCharges
0        1.0       29.850000     29.850000
1       34.0       56.950001   1889.500000
2        2.0       53.849998    108.150002
3       45.0       42.299999   1840.750000
4        2.0       70.699997    151.649994
...      ...             ...           ...
5038    24.0       84.800000   1990.500000
5039    72.0      103.200000   7362.900000
5040    11.0       29.600000    346.450000
5041     4.0       74.400000    306.600000
5042    66.0      105.650000   6844.500000

[5043 rows x 3 columns]

## Handling Categorical Features

In [16]:
train_cat = train["gender"]

In [20]:
train_cat = train_cat.array.reshape(-1 , 1)

In [21]:
from sklearn.preprocessing import OrdinalEncoder

cat_encoder = OrdinalEncoder()

train_cat_1hot = cat_encoder.fit_transform(train_cat) 

train_cat_1hot

array([[0.],
       [1.],
       [1.],
       ...,
       [0.],
       [1.],
       [1.]])

In [25]:
cat_encoder.categories_

[array(['Female', 'Male'], dtype=object)]

In [6]:
train

Column1  customerID  gender SeniorCitizen Partner Dependents  tenure  \
0           0  7590-VHVEG  Female            No     Yes         No       1   
1           1  5575-GNVDE    Male            No      No         No      34   
2           2  3668-QPYBK    Male            No      No         No       2   
3           3  7795-CFOCW    Male            No      No         No      45   
4           4  9237-HQITU  Female            No      No         No       2   
...       ...         ...     ...           ...     ...        ...     ...   
5038     2038  6840-RESVB    Male            No     Yes        Yes      24   
5039     2039  2234-XADUH  Female            No     Yes        Yes      72   
5040     2040  4801-JZAZL  Female            No     Yes        Yes      11   
5041     2041  8361-LTMKD    Male           Yes     Yes         No       4   
5042     2042  3186-AJIEK    Male            No      No         No      66   

     PhoneService     MultipleLines InternetService  ... DeviceProtection  \
0              No                No             DSL  ...               No   
1             Yes                No             DSL  ...              Yes   
2             Yes                No             DSL  ...               No   
3              No                No             DSL  ...              Yes   
4             Yes                No     Fiber optic  ...               No   
...           ...               ...             ...  ...              ...   
5038          Yes               Yes             DSL  ...              Yes   
5039          Yes               Yes     Fiber optic  ...              Yes   
5040           No  No phone service             DSL  ...               No   
5041          Yes               Yes     Fiber optic  ...               No   
5042          Yes                No     Fiber optic  ...              Yes   

     TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0             No          No              No  Month-to-month              Yes   
1             No          No              No        One year               No   
2             No          No              No  Month-to-month              Yes   
3            Yes          No              No        One year               No   
4             No          No              No  Month-to-month              Yes   
...          ...         ...             ...             ...              ...   
5038         Yes         Yes             Yes        One year              Yes   
5039          No         Yes             Yes        One year              Yes   
5040          No          No              No  Month-to-month              Yes   
5041          No          No              No  Month-to-month              Yes   
5042         Yes         Yes             Yes        Two year              Yes   

                  PaymentMethod MonthlyCharges TotalCharges  Churn  
0              Electronic check      29.850000    29.850000     No  
1                  Mailed check      56.950001  1889.500000     No  
2                  Mailed check      53.849998   108.150002    Yes  
3     Bank transfer (automatic)      42.299999  1840.750000     No  
4              Electronic check      70.699997   151.649994    Yes  
...                         ...            ...          ...    ...  
5038               Mailed check      84.800000  1990.500000     No  
5039    Credit card (automatic)     103.200000  7362.900000     No  
5040           Electronic check      29.600000   346.450000     No  
5041               Mailed check      74.400000   306.600000    Yes  
5042  Bank transfer (automatic)     105.650000  6844.500000     No  

[5043 rows x 22 columns]